ridevide/urls.py
from django.conf.urls import include, url
from django.contrib.auth.views import logout
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'ridevide.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^accounts/logout/$', logout, {'next_page': '/'}),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('ridevide_app.urls')),
]

ridevide_app/urls.py
from django.conf.urls import include, url
from ridevide_app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^browse/$', views.browse, name='browse'),
    url(r'^browse/(?P<ride_id>\d+)/$', views.browse_detail, name='browse_detail'),
    url(r'^browse/from_campus/$', views.browse_from_campus, name='browse_from_campus'),
    url(r'^browse/to_campus/$', views.browse_to_campus, name='browse_to_campus'),
    url(r'^delete_rider/(?P<ride_id>\d+)/$', views.delete_user_from_ride, name='delete_user_from_ride'),
    url(r'^add_rider/(?P<ride_id>\d+)/$', views.add_user_to_ride, name='add_user_to_ride'),
    url(r'^add/$', views.add, name='add'),
    url(r'^add/from_campus/$', views.add_from_campus, name='add_from_campus'),
    url(r'^add/to_campus/$', views.add_to_campus, name='add_to_campus'),
    url(r'^search/$', views.search, name='search'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^stats/$', views.stats, name='stats'),
    url(r'^stats/archives/$', views.archives, name='archives'),
]

ridevide_app/models.py
from django.db import models
from django.contrib.auth.models import User
from allauth.socialaccount.models import SocialAccount

class UserProfile(models.Model):

    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)

    def __unicode__(self):
        return "{}'s profile".format(self.user.username)

    def get_url(self):
        uid = SocialAccount.objects.filter(user_id=self.user.id)
        if len(uid):
            return uid[0].extra_data['link']
        else:
            return '#'

    def get_id(self):
        uid = SocialAccount.objects.filter(user_id=self.user.id)
        if len(uid):
            return uid[0].extra_data['id']
        else:
            return ''

    class Meta:
        db_table = 'user_profile'

User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])

class Ride(models.Model):
    departure = models.CharField(max_length=200)
    destination = models.CharField(max_length=200)
    date = models.DateField()
    time = models.TimeField()
    luggage = models.PositiveIntegerField()
    flight_number = models.CharField(max_length=200)
    riders = models.ManyToManyField(UserProfile)
    from_campus = models.BooleanField()

    def __unicode__(self):
        return "from %s to %s" % (self.departure, self.destination)

ridevide_app/forms.py
from django import forms
from bootstrap3_datetime.widgets import DateTimePicker

TIME_INPUT_FORMATS = ['%H:%M', '%I : %M %p']

LUGGAGE_NUMBER_CHOICES = [(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)]

CAMPUS_LOCATION_CHOICES = [('Campus', 'Campus'),
                          ]

OFF_CAMPUS_LOCATION_CHOICES = [("O'Hare Airport", "O'Hare Airport"),
                               ('Midway Airport', 'Midway Airport'),
                               ('Union Station', 'Union Station'),
                              ]

ALL_LOCATION_CHOICES = [('All', 'All')] + CAMPUS_LOCATION_CHOICES + OFF_CAMPUS_LOCATION_CHOICES

class AddRideForm(forms.Form):
    date = forms.DateField(
        widget=DateTimePicker(options={"format": "YYYY-MM-DD",
                                       "pickTime": False,
                                      }))
    time = forms.TimeField(
        input_formats=TIME_INPUT_FORMATS)

    luggage = forms.ChoiceField(choices=LUGGAGE_NUMBER_CHOICES)

    flight_number = forms.CharField()

class AddFromCampusRideForm(AddRideForm):
    #departure = forms.ChoiceField(
    #    choices=CAMPUS_LOCATION_CHOICES)
    departure = 'Campus'
    destination = forms.ChoiceField(
        choices=OFF_CAMPUS_LOCATION_CHOICES)

class AddToCampusRideForm(AddRideForm):
    departure = forms.ChoiceField(
        choices=OFF_CAMPUS_LOCATION_CHOICES)
    #destination = forms.ChoiceField(
    #    choices=CAMPUS_LOCATION_CHOICES)
    destination = 'Campus'

class FilterRidesForm(forms.Form):
    date = forms.DateField(
        required=False,
        widget=DateTimePicker(options={"format": "YYYY-MM-DD",
                                       "pickTime": False,
                                      }))
    departure = forms.ChoiceField(
        required=False,
        choices=ALL_LOCATION_CHOICES)
    destination = forms.ChoiceField(
        required=False,
        choices=ALL_LOCATION_CHOICES)

ridevide_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from ridevide_app import forms
from ridevide_app.models import Ride, UserProfile
import datetime
import itertools

### Helper Methods

def outsideTimeBan(time1, time2, constraint_minutes):
    d = datetime.date.today()
    dt1 = datetime.datetime.combine(d, time1)
    dt2 = datetime.datetime.combine(d, time2)
    if abs((dt1 - dt2).total_seconds()) > (constraint_minutes * 60):
        return True
    return False

# disallow users to sign up for two or more rides that are less than 30 minutes apart
def eligibleForRide(request, date, time):
    check_rides = request.user.profile.ride_set.filter(date=date);
    for ride in check_rides:
        if not outsideTimeBan(ride.time, time, 30):
            return False
    return True

### Views

def index(request):
    if request.user.is_authenticated():
        today = datetime.date.today().strftime('%Y-%m-%d')
        my_rides = request.user.profile.ride_set.filter(date__gte=today).order_by('date')
        if my_rides.count() == 0:
            return render(request, "ridevide_app/index.html")
        else:
            return browse_rides(request, my_rides, "My Upcoming Rides")
    else:
        return render(request, "ridevide_app/landing.html")

@login_required(login_url='/')
def browse(request):
    return render(request, "ridevide_app/browse.html")

@login_required(login_url='/')
def browse_detail(request, ride_id):
    ride = get_object_or_404(Ride, pk=ride_id)
    today = datetime.date.today()
    if ride.date < today:
        archived = True
    else:
        archived = False
    return render(request, "ridevide_app/browse_detail.html", dict(ride=ride, ride_id=ride_id, archived=archived))

@login_required(login_url='/')
def add_user_to_ride(request, ride_id):
    error = ''
    ride = get_object_or_404(Ride, pk=ride_id)
    if request.method == 'POST':
        if eligibleForRide(request, ride.date, ride.time):
            ride.riders.add(request.user.profile)
        else:
            error = 'Cannot join multiple rides within 30 minutes of each other. Remove yourself from the conflicting ride in order to join this ride.'
            return render(request, "ridevide_app/browse_detail.html", dict(ride=ride, ride_id=ride_id, error=error))
    return redirect("/browse/%d" % int(ride_id))

@login_required(login_url='/')
def delete_user_from_ride(request, ride_id):
    ride = get_object_or_404(Ride, pk=ride_id)
    if request.method == 'POST':
        ride.riders.remove(request.user.profile)
        if ride.riders.count() == 0:
            ride.delete()
            return redirect("/")
    return redirect("/browse/%d" % int(ride_id))

def browse_rides(request, rides, heading):
    formatted_rides = []
    for k, g in itertools.groupby(rides, lambda x: x.date):
        tmp_rides = []
        for ride in sorted(list(g), key = lambda r: r.time):
            tmp_rides.append(ride)
        formatted_rides.append(tmp_rides)
    return render(request, "ridevide_app/browse_rides.html", dict(heading=heading, formatted_rides=formatted_rides))

@login_required(login_url='/')
def browse_from_campus(request):
    today = datetime.date.today().strftime('%Y-%m-%d')
    from_campus_rides = Ride.objects.filter(from_campus=True, date__gte=today).order_by('date')
    return browse_rides(request, from_campus_rides, "Browse Rides from Campus")

@login_required(login_url='/')
def browse_to_campus(request):
    today = datetime.date.today().strftime('%Y-%m-%d')
    to_campus_rides = Ride.objects.filter(from_campus=False, date__gte=today).order_by('date')
    return browse_rides(request, to_campus_rides, "Browse Rides to Campus")

@login_required(login_url='/')
def search(request):
    if request.method == 'POST':
        form = forms.FilterRidesForm(request.POST)
        if form.is_valid():
            rides = Ride.objects.order_by('date')
            date = form.cleaned_data['date']
            departure = form.cleaned_data['departure']
            destination = form.cleaned_data['destination']
            if date:
                rides = rides.filter(date=date)
            if departure != "All":
                rides = rides.filter(departure=departure)
            if destination != "All":
                rides = rides.filter(destination=destination)

            if len(rides) == 0:
                return render(request, "ridevide_app/no_rides.html")
            else:
                return browse_rides(request, rides, "Search Results")
    else:
        form = forms.FilterRidesForm()
        return render(request, "ridevide_app/search.html", dict(form=form))

@login_required(login_url='/')
def add(request):
    return render(request, "ridevide_app/add.html")

@login_required(login_url='/')
def add_from_campus(request):
    if request.method == 'POST':
        form = forms.AddFromCampusRideForm(request.POST)
        if form.is_valid():
            date = form.cleaned_data['date']
            time = form.cleaned_data['time']
            luggage = form.cleaned_data['luggage']
            departure = 'Campus' #form.cleaned_data['departure']
            destination = form.cleaned_data['destination']
            flight_number = form.cleaned_data['flight_number']
            today = datetime.date.today()
            if date < today:
                error = 'Cannot enter a date in the past.'
                return render(request, "ridevide_app/add_rides.html", dict(form=form, heading="Add Ride from Campus", error=error))
            if eligibleForRide(request, date, time):
                r = Ride(date=date, time=time, luggage=luggage, departure=departure, destination=destination, flight_number=flight_number, from_campus=False)
                r.save()
                profile = request.user.profile
                r.riders.add(profile)
                return redirect("/browse/%d" % r.id)
            else:
                error = 'Cannot be in multiple rides within 30 minutes of each other. Remove yourself from the conflicting ride in order to create this ride.'
                return render(request, "ridevide_app/add_rides.html", dict(form=form, heading="Add Ride from Campus", error=error))
        else:
            return render(request, "ridevide_app/add_rides.html", dict(form=form, heading="Add Ride from Campus"))
    else:
        form = forms.AddFromCampusRideForm()
        return render(request, "ridevide_app/add_rides.html", dict(form=form, heading="Add Ride from Campus"))

@login_required(login_url='/')
def add_to_campus(request):
    if request.method == 'POST':
        form = forms.AddToCampusRideForm(request.POST)
        if form.is_valid():
            date = form.cleaned_data['date']
            time = form.cleaned_data['time']
            luggage = form.cleaned_data['luggage']
            departure = form.cleaned_data['departure']
            destination = 'Campus' #form.cleaned_data['destination']
            flight_number = form.cleaned_data['flight_number']
            today = datetime.date.today()
            if date < today:
                error = 'Cannot enter a date in the past.'
                return render(request, "ridevide_app/add_rides.html", dict(form=form, heading="Add Ride from Campus", error=error))
            if eligibleForRide(request, date, time):
                r = Ride(date=date, time=time, luggage = luggage, departure=departure, destination=destination, flight_number=flight_number, from_campus=False)
                r.save()
                profile = request.user.profile
                r.riders.add(profile)
                return redirect("/browse/%d" % r.id)
            else:
                error = 'Cannot be in multiple rides within 30 minutes of each other. Remove yourself from the conflicting ride in order to create this ride.'
                return render(request, "ridevide_app/add_rides.html", dict(form=form, heading="Add Ride to Campus", error=error))
        else:
            return render(request, "ridevide_app/add_rides.html", dict(form=form, heading="Add Ride to Campus"))
    else:
        form = forms.AddToCampusRideForm()
        return render(request, "ridevide_app/add_rides.html", dict(form=form, heading="Add Ride to Campus"))

@login_required(login_url='/')
def contact(request):
    return render(request, "ridevide_app/contact.html")

def stats(request):
    total_rides = Ride.objects.all()
    today = datetime.date.today()
    completed_rides = total_rides.filter(date__lt=today)
    completed_rides_with_2_riders = 0
    completed_rides_with_3_riders = 0
    completed_rides_with_4_riders = 0
    for completed_ride in completed_rides:
        num_riders = len(completed_ride.riders.all())
        if num_riders == 2:
            completed_rides_with_2_riders += 1
        if num_riders == 3:
            completed_rides_with_3_riders += 1
        if num_riders == 4:
            completed_rides_with_4_riders += 1
    completed_rides_with_more_than_2_riders = completed_rides_with_2_riders + completed_rides_with_3_riders + completed_rides_with_4_riders
    completed_rides_with_more_than_3_riders = completed_rides_with_3_riders + completed_rides_with_4_riders
    upcoming_rides = total_rides.filter(date__gte=today)
    users = UserProfile.objects.all()
    return render(request, "ridevide_app/stats.html", dict(total_rides=total_rides, completed_rides=completed_rides, upcoming_rides=upcoming_rides, users=users, completed_rides_with_more_than_2_riders=completed_rides_with_more_than_2_riders, completed_rides_with_more_than_3_riders=completed_rides_with_more_than_3_riders, completed_rides_with_4_riders=completed_rides_with_4_riders))

@login_required(login_url='/')
def archives(request):
    rides = Ride.objects.order_by('date')
    return browse_rides(request, rides, "Archived Rides")

ridevide_app/templates/ridevide_app/add.html
{% extends 'ridevide_app/base.html' %}

{% block extra_head %} 

<link href="/static/css/2-col-portfolio.css" rel="stylesheet">

{% endblock %}


{% block content %}

	<div class="container">

        <div class="row">

            <div class="col-lg-12">
                <h1 class="page-header">Add a Ride
                </h1>
            </div>

        </div>

        <div class="row">

            <div class="col-lg-6 col-md-6 portfolio-item">
                <a href="/add/from_campus">
                    <img class="img-responsive" src="/static/img/from_campus.jpg">
                </a>
                <h3><a href="/add/from_campus">From Campus</a>
                </h3>
            </div>

            <div class="col-lg-6 col-md-6 portfolio-item">
                <a href="/add/to_campus">
                    <img class="img-responsive" src="/static/img/to_campus.jpg">
                </a>
                <h3><a href="/add/to_campus">To Campus</a>
                </h3>
            </div>

        </div>

    </div>

{% endblock %}

ridevide_app/templates/ridevide_app/add_rides.html
{% extends 'ridevide_app/base.html' %}

{% block extra_head %} 

{{ form.media }}

{% endblock %}


{% block content %}

    <div class="content-section-b">

        <div class="add_ride_container">
        	
			<form method="post" class="add_ride_form">
				{% csrf_token %}

				<h2 class="text-center">{{ heading }}</h2>

				{% for field in form.visible_fields %}
					<div id="div_{{ field.html_name }}" class="form-group {% if field.errors %} has-error{% endif %}">
						{{ field.label_tag }}
						{{ field }}
						<div class="text-muted pull-right">
							<small>{{ field.help_text }}</small>
						</div>
						<div class="help-block">
							{{ field.errors }}
						</div>
					</div>
				{% endfor %}

				<div id="timePicker">
					<link rel="stylesheet" type="text/css" href="/static/css/wickedpicker.css">
					<script type="text/javascript" src="/static/js/wickedpicker.js"></script>
					<script type="text/javascript">
						const options = {
							now: "12:00",
							title: "Time",
							minutesInterval: 15
						};
						$('#id_time').wickedpicker(options);
					</script>
				</div>

				{% for hidden in forms.hidden_fields %}
					{{ hidden }}
				{% endfor %}

				<div class="form-group">
					<div class="button-container">
						<input type="submit" value="Add Ride" class="btn btn-primary btn-lg">
					</div>
				</div>
				
				<h3 class="text-danger">{{ error }}</h3>

			</form>
		</div>

    </div>

{% endblock %}

ridevide_app/templates/ridevide_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Ride Vide</title>

    <link rel="shortcut icon" href="/static/img/ridevide_favicon.ico">

    <meta property="og:image" content="http://www.ridevide.com/static/img/ridevide_gray_background.jpg">
    <meta property="og:description" content="Split rides with other UChicago students.">

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap-theme.css">

    <!-- Custom Google Web Font -->
    <link href="/static/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>

    <!-- Add custom CSS here -->
    <link href="/static/css/landing-page.css" rel="stylesheet">

    <!-- JavaScript -->
    <script src="/static/js/jquery-1.10.2.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>

    {% block extra_head %} {% endblock %}

    <link rel="stylesheet" type="text/css" href="/static/css/style.css">

    <script type="text/javascript">
        if(window.location.hash && window.location.hash == '#_=_') {
            window.location.hash = '';
        }
    </script>

</head>

<body>

    <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '{your-app-id}',
          cookie     : true,
          xfbml      : true,
          version    : '{api-version}'
        });
          
        FB.AppEvents.logPageView();
          
      };

      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "https://connect.facebook.net/en_US/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    </script>
    
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-logo" href="/"><img src="/static/img/ridevidelogo.png"></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-left navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/browse">Browse</a>
                    </li>
                    <li>
                        <a href="/add">Add</a>
                    </li>
                    <li>
                        <a href="/search">Search</a>
                    </li>
                </ul>
            </div>
            <div class="collapse navbar-collapse navbar-right navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <!--
                    <li>
                        <a href="#">About</a>
                    </li>
                    -->
                    <li>
                        <a href="/contact">Contact</a>
                    </li>
                    <li>
                        <a href="/accounts/logout">Logout</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="block_content">
    {% block content %} {% endblock %}
    </div>

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <a href="/">Home</a>
                        </li>
                        <!--
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#">About</a>
                        </li>
                        -->
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="/contact">Contact</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; Ride Vide. All Rights Reserved<a href="/stats">.</a></p>
                </div>
            </div>
        </div>
    </footer>

</body>

</html>

ridevide_app/templates/ridevide_app/browse.html
{% extends 'ridevide_app/base.html' %}

{% block extra_head %} 

<link href="/static/css/2-col-portfolio.css" rel="stylesheet">

{% endblock %}


{% block content %}

    <div class="container">

        <div class="row">

            <div class="col-lg-12">
                <h1 class="page-header">Browse Rides
                </h1>
            </div>

        </div>

        <div class="row">

            <div class="col-lg-6 col-md-6 portfolio-item">
                <a href="/browse/from_campus">
                    <img class="img-responsive" src="/static/img/from_campus.jpg">
                </a>
                <h3><a href="/browse/from_campus">From Campus</a>
                </h3>
            </div>

            <div class="col-lg-6 col-md-6 portfolio-item">
                <a href="/browse/to_campus">
                    <img class="img-responsive" src="/static/img/to_campus.jpg">
                </a>
                <h3><a href="/browse/to_campus">To Campus</a>
                </h3>
            </div>

        </div>

    </div>

{% endblock %}

ridevide_app/templates/ridevide_app/browse_detail.html
{% extends 'ridevide_app/base.html' %}

{% block content %}

	<script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '624070504367848',
          xfbml      : true,
          version    : 'v2.0'
        });
      };

      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "//connect.facebook.net/en_US/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    </script>

    <script>
    	function messageGroup(path) {
    		FB.ui({
			  	method: 'send',
			  	link: 'http://www.ridevide.com' + path,
			  	name: 'testname',
			  	to: '',
			  	description: 'testdescription',
			});
    	}
    </script>

	<div class="content-section-b">

				<h2 class = "text-center">
						<br> View Rides Details
				</h2>


		<div class="ride_detail_container">

			<h3>Date</h3>
			<p>{{ ride.date }}</p>

			<h3>Time</h3>
			<p>{{ ride.time }}</p>

			<h3>Departure</h3>
			<p>{{ ride.departure }}</p>

			<h3>Destination</h3>
			<p>{{ ride.destination }}</p>

			<h3>Luggage Count</h3>
			<p>{{ ride.luggage }}</p>

			<h3>Flight Number</h3>
			<p>{{ ride.flight_number }}</p>

			<h3>Riders</h3>
			{% for rider in ride.riders.all %}
				<form action="/delete_rider/{{ ride_id }}/" method="post">
					{% csrf_token %}
					<p>
						{{ rider.user.first_name }} {{ rider.user.last_name }} <a href = "mailto:"{{ rider.user.email }}>{{ rider.user.email }}</a>
						{% if request.user == rider.user and not archived %}
							<input type="submit" value="X" class="btn btn-sm btn-danger">
						{% endif %}
					</p>
				</form>
			{% endfor %}

			{% if request.user.profile in ride.riders.all %}
				<!--<button onclick="messageGroup({{ request.path }})">Message Group</button>-->
				<br>
				<a href="http://www.facebook.com/dialog/send?app_id=116412671734664&link=http://www.ridevide.com{{ request.path }}&redirect_uri=http://www.ridevide.com{{ request.path }}&to={% for rider in ride.riders.all %}{% if request.user != rider.user %}{{ rider.get_id }},{% endif %}{% endfor %}" target="_blank" class="btn btn-default">Message Group</a>
			{% elif ride.riders.all|length < 4 %}
				<form action="/add_rider/{{ ride_id }}/" method="post">
					{% csrf_token %}
					<br>
					<input type="submit" value="Join Ride" class="btn btn-primary btn-sm">
				</form>
			{% else %}
				<br>
				<h3 class="text-danger">Ride is Full</h3>
			{% endif %}


			<h3 class="text-danger">{{ error }}</h3>

		</div>

	</div>

{% endblock %}

ridevide_app/templates/ridevide_app/browse_rides.html
{% extends 'ridevide_app/base.html' %}

{% block extra_head %}

    <!-- Custom CSS for the '3 Col Portfolio' Template -->
    <link href="/static/css/3-col-portfolio.css" rel="stylesheet">

{% endblock %}

{% block content %}

    <div class="container">

        <div class="row">
            <br>
            <h1 class="text-center">{{ heading }}</h1>
        </div>

        {% for ride_group in formatted_rides %}

            <div class="row">

                <div class="col-lg-12">
                    <h1 class="page-header">{{ ride_group.0.date }}
                    </h1>
                </div>

            </div>

            <div class="row">

                {% for ride in ride_group %}
                    <a href="/browse/{{ ride.id }}">
                        <div class="col-md-4 portfolio-item ride_block {% if ride.riders.count >= 4 %} full_ride {% else %} available_ride {% endif %}">
                            <!--<a href="#project-link">
                                <img class="img-responsive" src="http://placehold.it/700x400">
                            </a>-->
                            <div class="ride_details">
                                <h3>{{ ride.departure }} -> {{ ride.destination }}
                                </h3>
                                <p>{{ ride.time }}</p>
                            </div>
                            <div class="ride_riders">
                                <h2>{{ ride.riders.count }}/4</h2>
                            </div>
                        </div>
                    </a>

                {% endfor %}

            </div>

        {% endfor %}

        <!--
        <hr>

        <div class="row text-center">

            <div class="col-lg-12">
                <ul class="pagination">
                    <li><a href="#">&laquo;</a>
                    </li>
                    <li class="active"><a href="#">1</a>
                    </li>
                    <li><a href="#">2</a>
                    </li>
                    <li><a href="#">3</a>
                    </li>
                    <li><a href="#">4</a>
                    </li>
                    <li><a href="#">5</a>
                    </li>
                    <li><a href="#">&raquo;</a>
                    </li>
                </ul>
            </div>

        </div>
        -->

    </div>
    <!-- /.container -->

{% endblock %}

ridevide_app/templates/ridevide_app/contact.html
{% extends 'ridevide_app/base.html' %}

{% block content %}

<div class="container">
	<br><br><br><br>
	<br><br><br><br>
  <h1 class="text-center"> contact us at: </h1>
	<h1 class="text-info text-center">ridevideteam@gmail.com</h1>
</div>

{% endblock %}

ridevide_app/templates/ridevide_app/index.html
{% extends 'ridevide_app/base.html' %}

{% block content %}

    <div class="intro-header">

        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>RIDE VIDE</h1>
                        <h3>A platform to split rides with other UChicago students.</h3>
                        <hr class="intro-divider">
                        <ul class="list-inline intro-social-buttons">
                            <li><a href="/browse" class="btn btn-default btn-lg"><span class="network-name">Browse Rides</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->

{% endblock %}